name: Gtihub-Action-IPTIME-WOL

#on : [push]
on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
  schedule:
  # 00*** 에 스케줄하였지만 실행은 30분 뒤에 되는 결과가 나와 30분 앞 당겼음
    - cron: '30 11 * * *'

jobs:
  getCurrentTime:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
      - uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY년 MM월 DD일 HH:mm:ss
          utcOffset: "+08:30"

  sendMagicPacket: 
    runs-on: ubuntu-latest
    steps:
    - name: curl
      - uses: indiesdev/curl@v1
        id: api
        with:
          url: ${{secrets.IPTIME_DOMAIN}}/cgi-bin/wol_apply.cgi?act=wakeup&mac=${{secrets.IPTIME_MAC}}
          method: 'GET'
          headers: '{"Authorization" : "Basic ${{secrets.IPTIME_BASIC}}", "Referer" : "http://192.168.0.1:80"}'
          
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ fromJson(steps.api.outputs.response).status_code == '200' }}
          if_true: "WOL 성공"
          if_false: "WOL 실패"
        
  createIssue: 
    runs-on: ubuntu-latest
    - name: create issue
    steps:
      - uses: nashmaniac/create-issue-action@v1.1
        with:
          title: ${{ getCurrentTime.steps.current-time.outputs.formattedTime }} 실행결과입니다.
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: result
          body: ${{ sendMagicPacket.steps.reporter.outputs.value }}
      